import { useState } from 'react';
import { api, label, type Detail } from '../../api';
import { Status } from '../../components/Primitives';
export function OpportunityDetail({ data, busy, perform, back }: { data: Detail; busy: boolean; perform: (fn: () => Promise<unknown>, message: string) => Promise<void>; back: () => void }) {
  const [hypothesis, setHypothesis] = useState('At least 3 of 100 relevant visitors will sign up within 14 days.');
  const latest = data.decisions[0]?.detail;
  return <><button className="text-button back" onClick={back}>← Opportunity board</button><div className="detail-heading"><div><span className="demo-label">Synthetic opportunity</span><h1>{data.title}</h1><p>{data.problemStatement}</p><p className="muted">Target customer · {data.targetUser}</p></div><button disabled={busy} className="primary" onClick={() => void perform(() => api(`/opportunities/${data.id}/run`, {}), 'Pipeline completed. Decision and ledger updated.')}>Run pipeline</button></div>
    <div className="detail-columns"><section className="panel"><div className="section-heading"><h2>Director decision</h2><Status value={data.status}/></div><div className="panel-body">{latest ? <><p>{latest.reasons.join(' ')}</p><h3>BUILD gates still closed</h3><ul className="reason-list">{latest.blockers.map(b => <li key={b}>{b}</li>)}</ul></> : <p>Run the pipeline to evaluate this evidence.</p>}</div></section><section className="panel critique"><div className="section-heading"><h2>Palermo’s challenge</h2><Status value={data.palermoVerdict}/></div><div className="panel-body"><ul className="reason-list">{data.palermo?.reasons.map(r => <li key={r}>{r}</li>)}</ul><p className="muted small">Adversarial rules, not a model opinion. Missing buying intent and duplicates are surfaced explicitly.</p></div></section></div>
    {data.scores && <section className="panel"><div className="section-heading"><h2>Evidence-backed scorecard</h2><strong>{data.totalScore} / 100</strong></div><div className="score-grid">{Object.entries(data.scores).filter(([k]) => k !== 'total').map(([key, entry]) => typeof entry === 'number' ? null : <div key={key}><span>{label(key.replace(/([A-Z])/g, '_$1'))}</span><strong>{entry.value}<small>/100</small></strong><div className="score-track"><i style={{ width: `${entry.value}%` }}/></div><p>{entry.reason}</p><div className="citation-links">{entry.evidenceIds.map(eid => <a key={eid} href={`#evidence-${eid}`}>E{data.evidence.findIndex(e => e.id === eid) + 1}</a>)}</div></div>)}</div></section>}
    <section className="panel"><div className="section-heading"><div><h2>Underlying evidence</h2><p>{data.evidenceReview.accepted.length} independent items · {data.evidenceReview.domains.length} domains · all synthetic and unverified</p></div><span className="count">{data.evidence.length}</span></div><div className="evidence-list">{data.evidence.map((e, i) => { const rejected = data.evidenceReview.rejected.find(r => r.id === e.id); return <article key={e.id} id={`evidence-${e.id}`}><div className="evidence-meta"><span className="evidence-number">E{i + 1}</span><strong>{label(e.signalType)}</strong><span>{Math.round(e.confidence * 100)}% confidence</span><span className="demo-label">Synthetic</span></div><p>{e.excerpt}</p><div className="evidence-source"><a href={e.sourceUrl} target="_blank" rel="noreferrer">{e.sourceUrl} ↗</a><span>{e.sourceIdentity} · {e.community} · {new Date(e.capturedAt).toLocaleDateString()}</span></div>{rejected && <p className="error-inline">Excluded: {rejected.reason}</p>}</article>; })}</div></section>
    {data.analysis && <section className="panel"><div className="section-heading"><h2>Analyst summary</h2></div><div className="panel-body"><p>{data.analysis.complexitySummary}</p><h3>Current alternatives</h3>{data.analysis.alternatives.length ? data.analysis.alternatives.map(a => <p key={a}>{a}</p>) : <p>No alternative evidence supplied.</p>}</div></section>}
    {data.status === 'VALIDATE' && <section className="panel"><div className="section-heading"><h2>Create an internal validation experiment</h2></div><form className="panel-body" onSubmit={e => { e.preventDefault(); void perform(() => api('/experiments', { opportunityId: data.id, hypothesis }), 'Synthetic experiment created. Open Experiments to record metrics.'); }}><label>Measurable hypothesis<textarea value={hypothesis} onChange={e => setHypothesis(e.target.value)} required minLength={12}/></label><p className="muted">Local record only. No website is built and nothing is sent or published.</p><button className="primary" disabled={busy}>Create experiment</button></form></section>}
    <section className="panel"><div className="section-heading"><h2>Agent runs</h2><span>{data.runs.length} recorded</span></div><div className="runs">{data.runs.map(r => <details key={r.id}><summary><strong>{r.agent}</strong><Status value={r.status}/><span>{r.duration} ms · {r.estimatedTokens} tokens · €{r.estimatedCost}</span></summary><pre>{JSON.stringify({ input: r.input, output: r.output, error: r.error }, null, 2)}</pre></details>)}</div></section>
  </>;
}
