import { euro, type Opportunity, type Overview as OverviewData, type LedgerEntry } from '../api';
import { OpportunityTable } from '../features/opportunities/OpportunityTable';
export function OverviewPage({ data, opportunities, ledger, onOpen, onNavigate }: { data: OverviewData; opportunities: Opportunity[]; ledger: LedgerEntry[]; onOpen: (id: string) => void; onNavigate: (page: string) => void }) {
  return <>
    <div className="mission"><div className="mission-icon">↗</div><div><h2>Find one problem worth validating.</h2><p>Demand before build. Every decision starts with evidence.</p></div><span className="phase">Phase 01 <span>/</span> Discovery</span></div>
    <section className="stats" aria-label="Overview metrics">{[
      ['Opportunities discovered', data.discovered, 'Synthetic research queue'], ['Under research', data.researching, 'More evidence needed'], ['Validation candidates', data.validationCandidates, 'Ready for a local experiment'], ['Experiments active', data.activeExperiments, `${data.killedExperiments} experiments killed`],
    ].map(([title, value, note]) => <div className="stat" key={title}><span>{title}</span><strong>{value}</strong><small>{note}</small></div>)}</section>
    <section className="financials" aria-label="Financial summary">{[['External Spend', data.externalSpend], ['AI/API Spend', data.aiSpend], ['Revenue', data.revenue], ['Net', data.net]].map(([title, value]) => <div key={title}><span>{title}</span><strong>{euro(Number(value))}</strong></div>)}<p><span className="live-dot"/> €0 spending limit enforced<br/><small>Only verified external revenue counts.</small></p></section>
    <section className="panel"><div className="section-heading"><div><h2>Opportunity pipeline</h2><p>Independent signals. Adversarial review. Explicit decisions.</p></div><button className="text-button" onClick={() => onNavigate('Opportunities')}>View all opportunities ↗</button></div><OpportunityTable items={opportunities} onOpen={onOpen}/></section>
    <div className="bottom-grid"><section className="panel"><div className="section-heading"><h2>How a decision is made</h2><span className="muted small">LOCAL RULE ENGINE</span></div><div className="pipeline-flow">{['Scout', 'Analyst', 'Scorer', 'Palermo', 'Director'].map((s, i) => <div key={s}><span className={s === 'Palermo' ? 'step adversarial' : 'step'}>{String(i + 1).padStart(2, '0')}</span><strong>{s}</strong><small>{['Collect & deduplicate', 'Group the evidence', 'Apply scoring rules', 'Challenge the case', 'Make the call'][i]}</small></div>)}</div><div className="panel-note">A veto blocks BUILD. Synthetic evidence never authorizes implementation.</div></section>
    <section className="panel"><div className="section-heading"><h2>Recent activity</h2><button className="text-button" onClick={() => onNavigate('Ledger')}>Audit trail ↗</button></div><div className="activity">{ledger.length ? ledger.slice(0, 3).map(e => <div key={e.id}><span className="activity-dot"/><div><strong>{e.agent}</strong><p>{e.action.toLowerCase().replaceAll('_', ' ')}</p></div><time>{new Date(e.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time></div>) : <p className="muted">No actions yet. Your first run will appear here.</p>}</div></section></div>
  </>;
}
